apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflare-tunnel-ingress-controller
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    # Secret ファイルの管理
    - repoURL: https://github.com/p-nasimonan/home-manifests.git
      targetRevision: main
      path: argocd-apps/secrets
    # Helm chart の管理
    - repoURL: https://helm.strrl.dev
      chart: cloudflare-tunnel-ingress-controller
      targetRevision: 0.0.12
      helm:
        valuesObject:
          secretRef:
              name: "my-cf-creds"
              apiTokenKey: "api-token"
              accountIDKey: "cloudflare-account-id"
              tunnelNameKey: "cloudflare-tunnel-name"
          cf-ingress:
            ingressClass:
              name: cloudflare
              isDefaultClass: false
            replicaCount: 1
  destination:
    server: https://kubernetes.default.svc
    namespace: cloudflare-tunnel-ingress-controller
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true