apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflare-tunnel-ingress-controller
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    # Sealed Secret と Helm chart の管理
    - repoURL: https://github.com/p-nasimonan/home-manifests.git
      targetRevision: main
      path: apps/cloudflare
    - repoURL: https://helm.strrl.dev
      chart: cloudflare-tunnel-ingress-controller
      targetRevision: 0.0.12
      helm:
        valuesObject:
          cloudflare:
            secretRef:
              name: "cloudflare-secrets"
              apiTokenKey: "api-token"
              accountIDKey: "cloudflare-account-id"
              tunnelNameKey: "cloudflare-tunnel-name"
          ingressClass:
            name: cloudflare
            isDefaultClass: false
          replicaCount: 1
  destination:
    server: https://kubernetes.default.svc
    namespace: cloudflare-tunnel-ingress-controller
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true