apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: fission

helmCharts:
  - name: fission-all
    repo: https://fission.github.io/fission-charts/
    version: v1.22.0
    releaseName: fission
    namespace: fission
    valuesFile: values.yaml
    includeCRDs: false

resources:
  - ingress.yaml
