apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: fission

resources:
  - ingress.yaml

helmCharts:
  - name: fission-all
    repo: https://fission.github.io/fission-charts/
    version: v1.22.0
    releaseName: fission
    valuesFile: values.yaml
    includeCRDs: false
