apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: github-actions-runner
  namespace: github-actions
spec:
  replicas: 1
  template:
    spec:
      organization: ieneko-saba
      githubAPICredentialsFrom:
        secretRef:
          name: github-actions-runner-secrets
      image: summerwind/actions-runner:latest
      imagePullPolicy: Always
