apiVersion: v2
name: grafana
description: Grafana with custom values
type: application
version: 0.1.0
appVersion: "10.5.5"

dependencies:
  - name: grafana
    version: "10.5.5"
    repository: "https://grafana.github.io/helm-charts"
