apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-secrets
  namespace: monitoring
spec:
  encryptedData:
    INFLUXDB_PASSWORD: AgAcjWsPd/VvdG1X1DEmFAd1OE9HY0hG9BeM9O4sQeK9HoO6n1WWMl0pkfQQDGEe7VbZtvtSBoD9aIcDOpXBn0jJl669/ZJI30HkgN1ioQoK5fW/8iblBfgw0wEAtbAPKzBfdkY6HdD4V0ZoVZZloxiLg4Uw8h/iitWHqV0zbPdOmdVNo6v7GBZWz5/PrDu/U5dIZ9OC0ouvuioPQ+5TYbTfPqWa16CjT8MLnA7y2z12jumIsqjmTNxCB4G8jKv/n4cMkd1im0sH5OeSue54R+EAinjx8TEwlfSh9AJKB4bxNIBY0OxMG3HCzpwNUe9TVvJEZq5ClLTwBmQ4Z5RO67o8373hdacm7LwmJ0KShnO+VC05zj6/FK3kb3z2dcfnsDDSeTDdePhONTYa/uf1Gmg3uzas8fKIQk3ZWAoewaASIUDMkplNKGNf2KjUvw8UGilW0IHnwNW7mZvpEcm+IgBApr10abW2Dxs2Kh+2JNfpTCYmZsS1aA12qbS5TAHMvBngkmd2WZH1rujX9LJVP0hrHfAg6+Dj4Cr7n5UTt2gBtPVJ3+/pqsDaC0CltW3Emu3GUPs9GphmQCj2cdLGkXU3xLb4B3wMOSOVhbqIP+mby8rBIXEQ/QO/GacKa11nlHey+TXmBhh28mad1JeXsodpNgc5U6tcYz1QfqwJG4pn0yq23sbvo3WvrvrXmVFQBXJ9XqALtOqW/pdlSHEypA==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-secrets
      namespace: monitoring
---