# データの永続化
persistence:
  enabled: true
  size: 10Gi
  storageClassName: nfs-client

# Sealed Secret から環境変数を注入
envFromSecret: grafana-secrets

# InfluxDBに接続する設定
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: InfluxDB
      type: influxdb
      url: http://192.168.0.31:8086
      database: homeassistant
      user: homeassistant
      secureJsonData:
        password: $__env{INFLUXDB_PASSWORD}
      isDefault: true

# 外部からアクセスするためのIngress設定
ingress:
  enabled: true
  ingressClassName: cloudflare
  hosts:
    - grafana.youkan.uk
