apiVersion: v1
kind: ConfigMap
metadata:
  name: misskey-config
  namespace: misskey
data:
  default.yml: |
    url: https://mi.youkan.uk
    
    # ポート設定
    port: 3000
    
    # データベース設定
    db:
      host: misskey-postgresql
      port: 5432
      db: misskey
      user: misskey
      pass: $MISSKEY_DB_PASS
      
    # Redis設定
    redis:
      host: misskey-redis-master
      port: 6379
      pass: $MISSKEY_REDIS_PASS
    
    # Meilisearch設定
    meilisearch:
      host: meilisearch
      port: 7700
      ssl: false
      apiKey: $MISSKEY_MEILISEARCH_API_KEY
    
    # ID生成方式
    id: 'aidx'
    
    # その他の設定
    allowedPrivateNetworks: []
    
    # ファイルストレージ設定
    drive:
      storage: 'fs'
      baseUrl: https://mi.youkan.uk/files
