architecture: standalone

fullnameOverride: misskey-redis

auth:
  enabled: true
  existingSecret: misskey-secrets
  existingSecretPasswordKey: REDIS_PASSWORD

master:
  persistence:
    enabled: true
    size: 5Gi
    storageClass: nfs-client
