# Sealed Secret の namespace
secretsNamespace: cloudflare-tunnel-ingress-controller
secretsName: my-cf-creds

cf-ingress:
  # IngressClass をこれに設定します
  ingressClass:
    name: cloudflare
    isDefaultClass: false
    
  # 必要に応じてレプリカ数など
  replicaCount: 1
  
  # Cloudflare 認証情報（Sealed Secret から参照）
  cloudflare:
    apiToken:
      valueFrom:
        secretKeyRef:
          name: my-cf-creds
          key: api-token
    accountId:
      valueFrom:
        secretKeyRef:
          name: my-cf-creds
          key: cloudflare-account-id
    tunnelName:
      valueFrom:
        secretKeyRef:
          name: my-cf-creds
          key: cloudflare-tunnel-name